%Matlab code for hypothesis No:3
% To verify the hypothsis,you have to change the choose training 
%and testing dataset as given in the report.
%Following code is taking 5% for training and 95% for testing

data = load('dataset.txt');
%data for training
trainingData=data(1:35,2:10); 

%targets values of training data
targetValue=data(1:35,11); 

%repalce the targets values with 0 and 1
targetValue(targetValue==2)=0;
targetValue(targetValue==4)=1;

%training function
trainFcn = 'traingdx';

%building the network
net = newff(trainingData',targetValue',20, {'tansig' 'tansig'},trainFcn,'mse');

%network parameters 
 net.trainParam.goal =0.01;
 net.trainParam.max_fail = 100;
 net.trainParam.lr=1;
 view(net);
 net = train(net, trainingData',targetValue');
 
 %testing data
 testData=data(36:699,2:10);
 
 %testing results generated by neural network
 outputs = net(testData');
 outputs=round(outputs);
 outputs=outputs';

 %finding out the percentage performance
 actualOutputs=data(36:699,11);
 actualOutputs(actualOutputs==2)=0;
 actualOutputs(actualOutputs==4)=1;
 CorrectAnswer=outputs-actualOutputs;
 countCorrectAnswer = length(find(CorrectAnswer==0));
 performance=(countCorrectAnswer/size(outputs,1))*100;

 
 
 